name: Parse JSON Files

on:
  push:

jobs:
  parse-json:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install fs path

    - name: Run the script
      run: node source-meta.js

    - name: Commit and Push changes
      uses: EndBug/add-and-commit@v2
      with:
        message: "Updated sourcesmeta.json"
        files: sourcesmeta.json
