name: Parse JSON Files

on:
  push:

jobs:
  parse-json:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt update && sudo apt install jq -y

    - name: Parse JSON Files
      run: |
        jq -r '.[] | {name: .name, description: .description, author: .author, download_link: "https://raw.githubusercontent.com/{{ github.repository_owner }}/{{ github.repository }}/{{ github.sha }}/cmd_sources/" + .name}' cmd_sources/*.json > sourcesmeta.json

    - name: Commit and Push changes
      uses: EndBug/add-and-commit@v2
      with:
        message: "Обновление sourcesmeta.json"
        files: sourcesmeta.json
